local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

ls.add_snippets("eruby", {
  s("html", { t("<html></html>") }),
  s("head", { t("<head></head>") }),
  s("body", { t("<body></body>") }),
  s("title", { t("<title></title>") }),
  s("meta", { t("<meta>") }),
  s("link", { t("<link rel=\"stylesheet\" href=\"\">") }),
  s("script", { t("<script></script>") }),
  s("style", { t("<style></style>") }),
  s("div", { t("<div></div>") }),
  s("span", { t("<span></span>") }),
  s("p", { t("<p></p>") }),
  s("h1", { t("<h1></h1>") }),
  s("h2", { t("<h2></h2>") }),
  s("h3", { t("<h3></h3>") }),
  s("h4", { t("<h4></h4>") }),
  s("h5", { t("<h5></h5>") }),
  s("h6", { t("<h6></h6>") }),
  s("ul", { t("<ul></ul>") }),
  s("ol", { t("<ol></ol>") }),
  s("li", { t("<li></li>") }),
  s("table", { t("<table></table>") }),
  s("tr", { t("<tr></tr>") }),
  s("td", { t("<td></td>") }),
  s("th", { t("<th></th>") }),
  s("thead", { t("<thead></thead>") }),
  s("tbody", { t("<tbody></tbody>") }),
  s("tfoot", { t("<tfoot></tfoot>") }),
  s("form", { t("<form action=\"\" method=\"\"></form>") }),
  s("input", { t("<input type=\"text\" name=\"\">") }),
  s("button", { t("<button></button>") }),
  s("label", { t("<label></label>") }),
  s("select", { t("<select></select>") }),
  s("option", { t("<option></option>") }),
  s("textarea", { t("<textarea></textarea>") }),
  s("a", { t("<a href=\"\"></a>") }),
  s("img", { t("<img src=\"\" alt=\"\">") }),
  s("video", { t("<video controls></video>") }),
  s("audio", { t("<audio controls></audio>") }),
  s("br", { t("<br>") }),
  s("hr", { t("<hr>") }),
  s("blockquote", { t("<blockquote></blockquote>") }),
  s("code", { t("<code></code>") }),
  s("pre", { t("<pre></pre>") }),
  s("iframe", { t("<iframe src=\"\"></iframe>") }),
})
